cmake_minimum_required(VERSION 3.16)
project(qt6_i486_smoke LANGUAGES CXX)
option(WITH_WIDGETS "Test GUI, Widgets and TLS" ON)
if(WITH_WIDGETS)
    find_package(Qt6 REQUIRED COMPONENTS Core Gui Widgets Network Xml)
else()
    find_package(Qt6 REQUIRED COMPONENTS Core)
endif()
add_executable(qt6-i486-smoke smoke.cpp)
target_link_libraries(qt6-i486-smoke PRIVATE Qt6::Core)
if(WITH_WIDGETS)
    target_link_libraries(qt6-i486-smoke PRIVATE Qt6::Gui Qt6::Widgets Qt6::Network Qt6::Xml)
endif()
